version: '3'
services:

  # API
  api:
    container_name: gohilreport-api
    restart: always
    build: .
    command: npm start
    working_dir: /usr/src/gohilReport-api
    environment:
      NODE_ENV: development
    links:
      - mongo
    ports:
      - "8000:8000"

  # MongoDB
  mongo:
    container_name: mongo
    image: mongo:4.0-xenial
    restart: always
    command: mongod
    ports:
      - "27017:27017" 
