version: '3'
services:

  # API
  gohilReport-api:
    container_name: gohilReportAPI
    command: NODE_ENV=development npm start
    working_dir: /usr/src/gohilReport-api
    links:
      - mongo
    ports:
      - "8000:8000"
    volumes:
      - /usr/src/gohilReport-api

  # MongoDB
  mongo:
    image: mongo
    ports:
      "27017:27017"
