version: '3'
services:

  # API
  api:
    container_name: gohilreport-api
    restart: always
    build: .
    command: npm start
    working_dir: /usr/src/gohilReport-api
    environment:
      NODE_ENV: development
    links:
      - mongo
    ports:
      - "8000:8000"

  # MongoDB
  mongo:
    container_name: mongo
    image: mongo:3.4-xenial
    restart: always
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: password
    command: mongod
    ports:
      - "27017:27017"
  
  # Mongo Web Client
  mongo-express:
    image: mongo-express:0.49
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
