version: '3.1'
services:

  # API
  gohilreport-api:
    container_name: gohilreport-api
    build: ./
    command: NODE_ENV=development npm start
    working_dir: /usr/src/gohilReport-api
    ports:
      - "8000:8000"

  # MongoDB
  mongo:
    image: mongo:3.4-xenial
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    command: mongod

  mongo-express:
    image: mongo-express:0.49
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
