version: '3'
services:

  # API
  api:
    container_name: api
    restart: always
    build: .
    command: npm start
    working_dir: /usr/src/gohilReport-api
    environment:
      NODE_ENV: development
    links:
      - mongo
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/gohilReport-api
    depends_on:
      - mongo

  # MongoDB
  mongo:
    container_name: mongo
    build: ./mongo
    restart: always
    command: mongod
    ports:
      - "27017:27017"
